### ISSUE TITLE
Which versions is it compatible with?

### ISSUE THREAD

**Issue by hamoid** [Awesome-Technologies/slack-matrix-migration#1]
Hi! I'm wondering what versions of Slack export has it been tested with?

It might be nice to include that info (or when it was last tested). 
As there's no issues, 1 commit only and no forks, I have doubts about being the first to try :)

**Comment by awesome-michael** [comment]
This was tested with Slack exports of Nov 2019. Unfortunately our priorities shifted away from this project so there are no recent tests.
