### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by rda0** [Awesome-Technologies/slack-matrix-migration#4]
Dear @awesome-michael, I am from https://github.com/isgphys/ and forked your project to https://github.com/rda0/slack-matrix-migration. Would you be willing to accept a PR, adding an opensource license, such as Apache-2.0 or whatever you prefer?

I would probably soon be ready for a PR including modifications to make it work with most recent synapse version, bug-fixes and additional config options.

Thanks a lot for your work

**Comment by awesome-michael** [comment]
I added a license. We would appreciate if you send a PR as our priorities unfortunately shifted away from this project this year.

**Comment by rda0** [comment]
Thank you. I will open a PR soon.
